spring:
  application:
    name: 'Reviews-Microservice'
  #h2  Database
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:reviewms
  jpa:
    hibernate:
      ddl-auto: 'update'
    show-sql: true
server:
  port: 8083
#euraka client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: 'http://localhost:8761/eureka/'
#Zipkin
management:
  tracing:
    sampling:
      probability: 1.0