spring:
  application:
    name: 'job-Microservice'
  #h2  Database
  h2:
     console:
        enabled: true
  datasource:
     url: jdbc:h2:mem:jobms
  jpa:
    hibernate:
      ddl-auto: 'update'
    show-sql: true
  cloud:
    config:
      enabled: false

server:
  port: 8081
#euraka client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: 'http://localhost:8761/eureka/'
#Zipkin
management:
  tracing:
    sampling:
      probability: 1.0

#ConfigServer
 #cloud:
 #config:
#server:
        #git:
         # uri: ''